- name: Install maven And Package app
  hosts: 127.0.0.1
  become: true
  tasks:
    - name: Install maven
      apt:
        name: maven
        update_cache: 'yes'
        state: present
    - name: Compile project
      shell: mvn compile
    - name: Package project
      shell: mvn package
- name: Manage web container
  hosts: worker1
  become: true
  tasks:
    - name: Update the System Packages
      apt:
        upgrade: 'yes'
        update_cache: 'yes'
    - name: Create a Tomcat User
      user:
        name: tomcat
    - name: Create a Tomcat Group
      group:
        name: tomcat
    - name: Install JAVA
      apt:
        name: default-jdk
        state: present
    - name: Create a Tomcat Directory
      file:
        path: /opt/tomcat9
        owner: tomcat
        group: tomcat
        mode: 755
        recurse: 'yes'
    - name: download & unarchive tomcat 9
      unarchive:
        src: >-
          https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.70/bin/apache-tomcat-9.0.70.tar.gz
        dest: /opt/tomcat9
        remote_src: 'yes'
        extra_opts:
          - '--strip-components=1'
    - name: Change ownership of tomcat directory
      file:
        path: /opt/tomcat9
        owner: tomcat
        group: tomcat
        mode: 'u+rwx,g+rx,o=rx'
        recurse: 'yes'
        state: directory
    - name: Creating a service file
      become: 'yes'
      copy:
        content: >-
          [Unit]

          Description=Tomcat Service

          Requires=network.target

          After=network.target

          [Service]

          Type=forking

          User=tomcat

          Environment="CATALINA_PID=/opt/tomcat9/logs/tomcat.pid"

          Environment="CATALINA_BASE=/opt/tomcat9"

          Environment="CATALINA_HOME=/opt/tomcat9"

          Environment="CATALINA_OPTS=-Xms512M -Xmx1024M -server
          -XX:+UseParallelGC"

          ExecStart=/opt/tomcat9/bin/startup.sh

          ExecStop=/opt/tomcat9/bin/shutdown.sh

          Restart=on-abnormal

          [Install]

          WantedBy=multi-user.target
        dest: /etc/systemd/system/tomcat.service
    - name: Start and Enable Tomcat 9 on sever
      systemd:
        name: tomcat
        state: started
        daemon_reload: true
    - name: Copy project to web container
      copy:
        src: ./target/addressbook-2.0.war
        dest: /opt/tomcat9/webapps/

